### ISSUE TITLE
Question about Avatar Physics

### ISSUE THREAD

**Issue by sachaamm** [jonlab/NewAtlantis#48]
I want to put some cloth elements in the Chicago space , so i try to assign to my cloth the avatar colliders . But it were not so efficient , because the eyes sphere colliders are really tiny.
Just a question here : 
- What is the collider for avatar ? only the eyes colliders? I tried to add a capsule collider but the avatar is now flying up from the scene.

**Comment by jonlab** [comment]
I am planning to remove the eyes (or at least the eyes colliders) as we have issues with the navigation (is some cases the movement is laggy and this is because of the eyes colliders). The avatar should have only one collider.
Do you really think that we can properly network synchronize cloth elements ?

**Comment by sachaamm** [comment]
Yes , you're right to wonder it . I think it depends on the colliding synchronizing
